# 옮긴이:

# 1 가중치 규제

## 1.1 `tf.keras.regularizers.l2`

- L2 규제 벌칙을 적용하는 규제


- L2 규제 벌칙은 다음과 같이 계산:
```python
loss = l2 * reduce_sum(square(x))
```    
    
- L2 는 문자열 식별자로 층에 전달될 것이다. 이 경우, 기본값 `l2=0.01` 사용
```python
dense = tf.keras.layers.Dense(3, kernel_reqularizer='12')
```

**서명:**

```python
regularizers.l2(l2=0.01, **kwargs)
```

- 인자:
  - `l2`: 부동소수점; L2 규제 인자.

**소스:**

```python
@keras_export("keras.regularizers.L2", "keras.regularizers.l2")
class L2(Regularizer):
    def __init__(self, l2=0.01, **kwargs):
        l2 = kwargs.pop("l", l2)  # Backwards compatibility
        if kwargs:
            raise TypeError(f"Argument(s) not recognized: {kwargs}")

        l2 = 0.01 if l2 is None else l2
        _check_penalty_number(l2)

        self.l2 = backend.cast_to_floatx(l2)

    def __call__(self, x):
        # equivalent to "self.l2 * tf.reduce_sum(tf.square(x))"
        return 2.0 * self.l2 * tf.nn.l2_loss(x)

    def get_config(self):
        return {"l2": float(self.l2)}
```

## 1.2 `tf.keras.regularizers.l1`

- L1 규제 벌칙을 적용하는 규제


- L1 규제 벌칙은 다음과 같이 계산:
```python
loss = l2 * reduce_sum(abs(x))
```    
    
- L2 는 문자열 식별자로 층에 전달될 것이다. 이 경우, 기본값 `l1=0.01` 사용
```python
dense = tf.keras.layers.Dense(3, kernel_reqularizer='11')
```

**서명:**


```python
regularizers.l1(l1=0.01, **kwargs)
```

- 인자:
  - `l1`: 부동소수점; L1 규제 인자.

**소스:**

```python
@keras_export("keras.regularizers.L1", "keras.regularizers.l1")
class L1(Regularizer):
    def __init__(self, l1=0.01, **kwargs):
        l1 = kwargs.pop("l", l1)  # Backwards compatibility
        if kwargs:
            raise TypeError(f"Argument(s) not recognized: {kwargs}")

        l1 = 0.01 if l1 is None else l1
        _check_penalty_number(l1)

        self.l1 = backend.cast_to_floatx(l1)

    def __call__(self, x):
        return self.l1 * tf.reduce_sum(tf.abs(x))

    def get_config(self):
        return {"l1": float(self.l1)}
```

## 1.3 `tf.keras.regularizers.l1_l2`

- L1 및 L2 규제 벌칙을 적용하는 규제


- L1 규제 벌칙은 다음과 같이 계산:
```python
loss = l2 * reduce_sum(abs(x))
```    

- L2 규제 벌칙은 다음과 같이 계산:
```python
loss = l2 * reduce_sum(square(x))
```

**서명:**


```python
regularizers.l1_l2(l1=0.01, l2=0.01)
```

- 인자:
  - `l1`: 부동소수점; L1 규제 인자.
  - `l2`: 부동소수점; L2 규제 인자.
  
- 반환:
  - 주어진 규제 인자로 L1L2 규제 반환

**소스:**

```python
keras_export("keras.regularizers.l1_l2")
def l1_l2(l1=0.01, l2=0.01):
    return L1L2(l1=l1, l2=l2)
```

# 2 드롭아웃 규제

## 2.1 `tf.keras.layers.Dropout`

- 입력에 드롭아웃 적용.


- 드롭아웃 층은 훈련 시간동안 각 단계에서 `rate` 빈도를 가지고 무작위로 입력 유닛을 0으로 설정하는데, 이는 과적합을 방지하는 데 도움을 준다.
0으로 설정되지 않은 입력은 모든 입력에 대한 합계가 변경되지 않도록 1/(1 - rate)만큼 확장된다.


- 드롭아웃 층은 오직 `training`이 참으로 설정될 때에만 적용되는데 이것은 추론 동안에 어떤 값도 제외되지 않는다.
`model.fit`을 사용할 때, `training`은 자동적을 적절하게 참으로 설정될 것이고, 다른 문맥에서는, 층을 호출할 때 명시적으로 kwarg을 참으로 설정 할 수 있다.


- (이것은 드롭아웃 층에 대하여 `trainable=False`와 대조된다. 드롭아웃에는 훈련 중에 동결될 수 있는 변수/가중치가 없기 때문에 `trainable`은 층의 동작에 영향을 미치지 않는다.)

**서명:**


```python
layers.Dropout(rate, noise_shape=None, seed=None, **kwargs)
```

- 인자:
  - `rate`: 0 과 1 사이의 부동소수점. 제외시킬 입력 유닛의 비율.
  - `noise_shape`: 입력과 곱해질 이진 드롭아웃 마스크의 형태를 표현하는 1D 정수 텐서. 
     예를 들어, 입력이 `(batch_size, timesteps, features)` 형태를 가지고 있고 드롭아웃 마스크가 모든 timesteps에 대하여 동일하기를 원하면, `noise_shape=(batch_size, 1, features)`를 사용할 수 있다.
  - `seed`: 무작위 시드로 사용될 파이썬 정수.
  

- 호출 인자:
  - `inputs`: (모든 순위의) 입력 텐서.
  - `training`: 층이 훈련 모드(드롭아웃 추가) 또는 추론 모드(아무것도 하지 않음) 작동 여부를 지시하는 Python 참/거짓.

**소스:**

```python
@keras_export("keras.layers.Dropout")
class Dropout(base_layer.BaseRandomLayer):
    def __init__(self, rate, noise_shape=None, seed=None, **kwargs):
        super().__init__(seed=seed, **kwargs)
        if isinstance(rate, (int, float)) and not 0 <= rate <= 1:
            raise ValueError(
                f"Invalid value {rate} received for "
                f"`rate`, expected a value between 0 and 1."
            )
        self.rate = rate
        self.noise_shape = noise_shape
        self.seed = seed
        self.supports_masking = True

    def _get_noise_shape(self, inputs):
        # 드롭아웃의 하위 클래스는 `_get_noise_shape(self, inputs)`를 구현할 수 있으며, 
        # 이는 `self.noise_shape`를 재정의하고 동적으로 크기가 조정된 입력으로 
        # 사용자 정의 잡음 형태를 허용한다.
        if self.noise_shape is None:
            return None

        concrete_inputs_shape = tf.shape(inputs)
        noise_shape = []
        for i, value in enumerate(self.noise_shape):
            noise_shape.append(
                concrete_inputs_shape[i] if value is None else value
            )
        return tf.convert_to_tensor(noise_shape)

    def call(self, inputs, training=None):
        if training is None:
            training = backend.learning_phase()

        def dropped_inputs():
            return self._random_generator.dropout(
                inputs, self.rate, noise_shape=self._get_noise_shape(inputs)
            )

        output = control_flow_util.smart_cond(
            training, dropped_inputs, lambda: tf.identity(inputs)
        )
        return output

    def compute_output_shape(self, input_shape):
        return input_shape

    def get_config(self):
        config = {
            "rate": self.rate,
            "noise_shape": self.noise_shape,
            "seed": self.seed,
        }
        base_config = super().get_config()
        return dict(list(base_config.items()) + list(config.items()))
```

**사용례:**

In [15]:
import tensorflow as tf
import numpy as np
tf.random.set_seed(0)
layer = tf.keras.layers.Dropout(.2, input_shape=(2,))
data = np.arange(10).reshape(5, 2).astype(np.float32)
print(data)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [16]:
outputs = layer(data, training=True)
print(outputs)

tf.Tensor(
[[ 0.    1.25]
 [ 2.5   3.75]
 [ 5.    6.25]
 [ 7.5   8.75]
 [10.    0.  ]], shape=(5, 2), dtype=float32)


In [17]:
outputs = layer(data) # training=None
print(outputs)

tf.Tensor(
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]], shape=(5, 2), dtype=float32)
